"""Shared build/version metadata for diagnostics and MCP config output."""

from __future__ import annotations

import os


ADDON_ID = "claude_blender"
ADDON_NAME = "Blender Agent Bridge"
ADDON_VERSION_TUPLE = (0, 1, 0)
ADDON_VERSION = "0.1.0"
BLENDER_VERSION_MIN_TUPLE = (5, 1, 0)
BLENDER_VERSION_MIN = "5.1.0"
BRIDGE_VERSION = "0.2"
MCP_SERVER_VERSION = "0.1.0"
MCP_CONFIG_VERSION = "1"

MCP_CONFIG_NOTE = (
    "Generated by Blender Agent Bridge; refresh or restart the MCP client after replacing this config."
)


def addon_root():
    return os.path.dirname(os.path.abspath(__file__))


def mcp_server_path():
    return os.path.join(addon_root(), "mcp_server.py")


def mcp_config_env(token=""):
    env = {
        "CLAUDE_BLENDER_ADDON_ID": ADDON_ID,
        "CLAUDE_BLENDER_ADDON_VERSION": ADDON_VERSION,
        "CLAUDE_BLENDER_BRIDGE_VERSION": BRIDGE_VERSION,
        "CLAUDE_BLENDER_MCP_SERVER_VERSION": MCP_SERVER_VERSION,
        "CLAUDE_BLENDER_MCP_CONFIG_VERSION": MCP_CONFIG_VERSION,
        "CLAUDE_BLENDER_MCP_CONFIG_NOTE": MCP_CONFIG_NOTE,
    }
    if token:
        env["BLENDER_BRIDGE_TOKEN"] = str(token)
    return env


def mcp_config(bridge_url, *, token="", command="python"):
    return {
        "mcpServers": {
            "blender": {
                "command": command,
                "args": [
                    mcp_server_path(),
                    "--bridge-url",
                    str(bridge_url or ""),
                ],
                "env": mcp_config_env(token),
            }
        }
    }


def diagnostics_dict(*, bridge_url="", blender_version=""):
    return {
        "addon_id": ADDON_ID,
        "addon_name": ADDON_NAME,
        "addon_version": ADDON_VERSION,
        "addon_path": addon_root(),
        "blender_version_min": BLENDER_VERSION_MIN,
        "blender_version": str(blender_version or ""),
        "bridge_version": BRIDGE_VERSION,
        "bridge_url": str(bridge_url or ""),
        "mcp_server_version": MCP_SERVER_VERSION,
        "mcp_server_path": mcp_server_path(),
        "mcp_config_version": MCP_CONFIG_VERSION,
    }


def diagnostics_summary():
    return (
        f"{ADDON_NAME} {ADDON_VERSION} | "
        f"Bridge {BRIDGE_VERSION} | MCP {MCP_SERVER_VERSION} | Config {MCP_CONFIG_VERSION}"
    )
