"""Shared build/version metadata for diagnostics and MCP config output."""

from __future__ import annotations

import hashlib
import os


ADDON_ID = "claude_blender"
ADDON_NAME = "Blender Agent Bridge"
ADDON_VERSION_TUPLE = (0, 1, 1)
ADDON_VERSION = "0.1.1"
BLENDER_VERSION_MIN_TUPLE = (5, 0, 0)
BLENDER_VERSION_MIN = "5.0.0"
BRIDGE_VERSION = "0.2"
MCP_SERVER_VERSION = "0.1.1"
MCP_CONFIG_VERSION = "1"

MCP_CONFIG_NOTE = (
    "Generated by Blender Agent Bridge; refresh or restart the MCP client after replacing this config."
)
SOURCE_HASH_EXTENSIONS = (".py", ".toml")
SOURCE_HASH_EXCLUDES = {"__pycache__", ".git", ".mypy_cache", ".pytest_cache"}


def addon_root():
    return os.path.dirname(os.path.abspath(__file__))


def mcp_server_path():
    return os.path.join(addon_root(), "mcp_server.py")


def source_tree_hash(root=None):
    root = os.path.abspath(root or addon_root())
    digest = hashlib.sha256()
    for current_root, dirnames, filenames in os.walk(root):
        dirnames[:] = [name for name in sorted(dirnames) if name not in SOURCE_HASH_EXCLUDES]
        for filename in sorted(filenames):
            if not filename.endswith(SOURCE_HASH_EXTENSIONS):
                continue
            path = os.path.join(current_root, filename)
            relpath = os.path.relpath(path, root).replace(os.sep, "/")
            digest.update(relpath.encode("utf-8"))
            digest.update(b"\0")
            try:
                with open(path, "rb") as handle:
                    for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                        digest.update(chunk)
            except OSError:
                digest.update(b"<unreadable>")
            digest.update(b"\0")
    return digest.hexdigest()


def expected_source_hash_from_env():
    return str(os.environ.get("CLAUDE_BLENDER_ADDON_SOURCE_HASH") or "").strip()


def source_hash_status(actual_hash=None, expected_hash=None):
    actual = str(actual_hash or source_tree_hash()).strip()
    expected = str(expected_hash if expected_hash is not None else expected_source_hash_from_env()).strip()
    if not expected:
        return {
            "actual": actual,
            "expected": "",
            "match": None,
            "status": "not_provided",
            "message": "No expected add-on source hash was provided by the MCP config environment.",
        }
    match = actual == expected
    return {
        "actual": actual,
        "expected": expected,
        "match": match,
        "status": "match" if match else "mismatch",
        "message": "Add-on source hash matches MCP config." if match else "Add-on source hash differs from MCP config.",
    }


def mcp_config_env(token=""):
    source_hash = source_tree_hash()
    env = {
        "CLAUDE_BLENDER_ADDON_ID": ADDON_ID,
        "CLAUDE_BLENDER_ADDON_VERSION": ADDON_VERSION,
        "CLAUDE_BLENDER_ADDON_SOURCE_HASH": source_hash,
        "CLAUDE_BLENDER_BRIDGE_VERSION": BRIDGE_VERSION,
        "CLAUDE_BLENDER_MCP_SERVER_VERSION": MCP_SERVER_VERSION,
        "CLAUDE_BLENDER_MCP_CONFIG_VERSION": MCP_CONFIG_VERSION,
        "CLAUDE_BLENDER_MCP_CONFIG_NOTE": MCP_CONFIG_NOTE,
    }
    if token:
        env["BLENDER_BRIDGE_TOKEN"] = str(token)
    return env


def mcp_config(bridge_url, *, token="", command="python"):
    return {
        "mcpServers": {
            "blender": {
                "command": command,
                "args": [
                    mcp_server_path(),
                    "--bridge-url",
                    str(bridge_url or ""),
                ],
                "env": mcp_config_env(token),
            }
        }
    }


def diagnostics_dict(*, bridge_url="", blender_version=""):
    source_hash = source_tree_hash()
    hash_status = source_hash_status(source_hash)
    return {
        "addon_id": ADDON_ID,
        "addon_name": ADDON_NAME,
        "addon_version": ADDON_VERSION,
        "addon_path": addon_root(),
        "addon_source_hash": source_hash,
        "expected_addon_source_hash": hash_status["expected"],
        "addon_source_hash_match": hash_status["match"],
        "addon_source_hash_status": hash_status["status"],
        "addon_source_hash_message": hash_status["message"],
        "blender_version_min": BLENDER_VERSION_MIN,
        "blender_version": str(blender_version or ""),
        "bridge_version": BRIDGE_VERSION,
        "bridge_url": str(bridge_url or ""),
        "mcp_server_version": MCP_SERVER_VERSION,
        "mcp_server_path": mcp_server_path(),
        "mcp_config_version": MCP_CONFIG_VERSION,
    }


def diagnostics_summary():
    source_hash = source_tree_hash()[:12]
    return (
        f"{ADDON_NAME} {ADDON_VERSION} | "
        f"Bridge {BRIDGE_VERSION} | MCP {MCP_SERVER_VERSION} | Config {MCP_CONFIG_VERSION} | Source {source_hash}"
    )
